In [1]:
import cv2
import numpy as np
import mahotas
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from collections import Counter
from skimage.color import rgb2lab, deltaE_cie76
import os

## Training

In [47]:
image = cv2.imread('cal7.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ctrnfeature = cv2.HuMoments(cv2.moments(image)).flatten()

ctrnfeature

array([ 2.15852120e-03,  5.84739907e-07,  1.53415895e-10,  5.10416514e-11,
        1.76939384e-21,  1.12989118e-15, -4.15570922e-21])

In [2]:
image = cv2.imread('cal7.jpg')
cmeans = cv2.mean(image)
cmeans = cmeans[:3]
cmeans

(60.9188654602057, 91.8586662482687, 63.7094884363458)

In [48]:
image1 = cv2.imread('cal1.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature1 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature1

array([1.46390300e-03, 1.61246124e-07, 2.50335379e-11, 1.77419819e-11,
       3.16456867e-22, 6.85112054e-15, 1.99153104e-22])

In [3]:
image1 = cv2.imread('cal1.jpg')
cmeans1 = cv2.mean(image1)
cmeans1 = cmeans1[:3]
cmeans1

(72.04148011086745, 136.5312911785357, 104.89825334878681)

In [49]:
image1 = cv2.imread('cal2.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature2 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature2

array([ 1.70888965e-03,  2.30722177e-07,  3.54018529e-11,  3.50350214e-11,
        6.15143656e-22,  1.28808776e-14, -1.06958573e-21])

In [17]:
image1 = cv2.imread('cal2.jpg')
cmeans2 = cv2.mean(image1)
cmeans2 = cmeans2[:3]
cmeans2

(62.4306144679132, 111.86057729301324, 84.15770347206191)

In [50]:
image1 = cv2.imread('cal4.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature3 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature3

array([ 2.08983086e-03,  3.54118195e-07,  6.98846938e-11,  2.51818587e-10,
        3.10511685e-20,  1.27296858e-13, -1.23197679e-20])

In [4]:
image1 = cv2.imread('cal4.jpg')
cmeans3 = cv2.mean(image1)
cmeans3 = cmeans3[:3]
cmeans3

(80.21293553670247, 101.02555470784506, 73.04836232503256)

In [51]:
image1 = cv2.imread('cal8.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature4 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature4

array([1.44069664e-03, 1.49771551e-07, 3.29588288e-11, 6.86504237e-11,
       3.18829014e-21, 2.55543565e-14, 7.05936850e-22])

In [5]:
image1 = cv2.imread('cal8.jpg')
cmeans4 = cv2.mean(image1)
cmeans4 = cmeans4[:3]
cmeans4

(69.90505562208243, 133.3929869046245, 116.10692653027854)

In [52]:
image1 = cv2.imread('cal9.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature5 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature5

array([1.21871278e-03, 1.21748064e-07, 1.31382330e-11, 1.63411820e-11,
       2.17347231e-22, 5.64102518e-15, 1.00453453e-22])

In [6]:
image1 = cv2.imread('cal9.jpg')
cmeans5 = cv2.mean(image1)
cmeans5 = cmeans5[:3]
cmeans5

(97.95740806866857, 162.4566069407574, 137.59537079117294)

In [53]:
image1 = cv2.imread('cal10.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature6 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature6

array([ 1.45858875e-03,  2.54902633e-07,  6.17003243e-13,  5.88660822e-12,
       -4.50422407e-25, -6.59575191e-17,  1.12096255e-23])

In [7]:
image1 = cv2.imread('cal10.jpg')
cmeans6 = cv2.mean(image1)
cmeans6 = cmeans6[:3]
cmeans6

(79.26529326731944, 143.40890245876938, 114.79335408491075)

In [54]:
image1 = cv2.imread('cal11.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
ctrnfeature7 = cv2.HuMoments(cv2.moments(image1)).flatten()

ctrnfeature7

array([ 2.02890412e-03,  3.27930981e-07,  1.69708147e-11,  2.04248524e-11,
       -3.78701108e-22,  1.16235001e-14, -3.44846650e-23])

In [8]:
image1 = cv2.imread('cal11.jpg')
cmeans7 = cv2.mean(image1)
cmeans7 = cmeans7[:3]
cmeans7

(57.26044632322766, 96.32835904637324, 75.24585279044193)

In [55]:
image2 = cv2.imread('orange1.jpg')
image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
otrnfeature = cv2.HuMoments(cv2.moments(image2)).flatten()

otrnfeature

array([ 9.53073152e-04,  6.55210456e-10,  8.27789487e-14,  1.96454553e-12,
       -5.53430429e-25, -2.18274266e-17, -5.66875989e-25])

In [9]:
image2 = cv2.imread('orange1.jpg')
omeans = cv2.mean(image2)
omeans = omeans[:3]
omeans

(128.02419166666667, 186.94775, 245.15874444444447)

In [56]:
image3 = cv2.imread('orange2.png')
image3 = cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)
otrnfeature1 = cv2.HuMoments(cv2.moments(image3)).flatten()

otrnfeature1

array([ 9.70012699e-04,  1.94311126e-08,  1.35112988e-12,  1.01178534e-12,
        1.15492858e-24,  1.41001709e-16, -2.56135933e-25])

In [10]:
image3 = cv2.imread('orange2.png')
omeans1 = cv2.mean(image3)
omeans1 = omeans1[:3]
omeans1

(104.41241551956782, 183.2625488111502, 234.00462964132063)

In [57]:
image3 = cv2.imread('orange4.jpg')
image3 = cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)
otrnfeature2 = cv2.HuMoments(cv2.moments(image3)).flatten()

otrnfeature2

array([ 8.34835256e-04,  9.94076993e-09,  9.43272208e-14,  7.91542970e-14,
       -3.94271380e-27, -1.83434857e-18,  5.58883184e-27])

In [11]:
image3 = cv2.imread('orange4.jpg')
omeans2 = cv2.mean(image3)
omeans2 = omeans2[:3]
omeans2

(176.86999987918765, 217.6852627064381, 240.9748106266536)

In [58]:
image3 = cv2.imread('orange5.jpeg')
image3 = cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)
otrnfeature3 = cv2.HuMoments(cv2.moments(image3)).flatten()

otrnfeature3

array([ 8.56785637e-04,  4.18048637e-10,  2.43460861e-14,  5.75112093e-13,
       -2.99327834e-26,  3.71332046e-18,  6.11159150e-26])

In [12]:
image3 = cv2.imread('orange5.jpeg')
omeans3 = cv2.mean(image3)
omeans3 = omeans3[:3]
omeans3

(166.58676875, 207.41586875000002, 244.22405625000002)

## Testing

In [59]:
image = cv2.imread('orange3.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
otstfeature = cv2.HuMoments(cv2.moments(image)).flatten()

otstfeature

array([ 9.05230729e-04,  4.25375126e-09,  2.16962866e-13,  7.32764527e-13,
       -2.70287361e-25, -3.51096538e-17, -1.10948282e-25])

In [13]:
image2 = cv2.imread('orange3.jpg')
otmeans = cv2.mean(image2)
otmeans = otmeans[:3]
otmeans

(153.23337442783034, 200.61207059302208, 236.76436313701558)

In [60]:
image = cv2.imread('cal5.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ctstfeature = cv2.HuMoments(cv2.moments(image)).flatten()

ctstfeature

array([ 2.07265467e-03,  3.44668672e-07,  8.26402057e-11,  2.43499971e-10,
        3.25048992e-20,  1.26418118e-13, -1.16859970e-20])

In [14]:
image2 = cv2.imread('cal5.jpg')
ctmeans = cv2.mean(image2)
ctmeans = ctmeans[:3]
ctmeans

(80.60831792195638, 101.70559377034506, 74.58150497436525)

In [61]:
image = cv2.imread('cal6.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ctstfeature1 = cv2.HuMoments(cv2.moments(image)).flatten()

ctstfeature1

array([1.45420763e-03, 8.71169259e-08, 1.46332557e-10, 1.25762272e-10,
       1.65463296e-20, 3.55026131e-14, 4.15756944e-21])

In [15]:
image2 = cv2.imread('cal6.jpg')
ctmeans1 = cv2.mean(image2)
ctmeans1 = ctmeans1[:3]
ctmeans1

(100.53836349487305, 125.24773056030274, 102.12571640014649)

In [62]:
image = cv2.imread('cal7.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ctstfeature2 = cv2.HuMoments(cv2.moments(image)).flatten()

ctstfeature2

array([ 2.15852120e-03,  5.84739907e-07,  1.53415895e-10,  5.10416514e-11,
        1.76939384e-21,  1.12989118e-15, -4.15570922e-21])

## Haralick

In [63]:
image = cv2.imread('cal1.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # compute the haralick texture feature vector
haralick = mahotas.features.haralick(gray).mean(axis=0)
    # return the result

haralick

array([ 1.37987436e-03,  1.26396225e+01,  9.97128573e-01,  2.20092647e+03,
        5.82420896e-01,  2.39422615e+02,  8.79106625e+03,  8.49442703e+00,
        1.03799574e+01,  1.12431756e-03,  2.27823159e+00, -6.17120367e-01,
        9.99949307e-01])

In [64]:
image = cv2.imread('cal2.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # compute the haralick texture feature vector
haralick = mahotas.features.haralick(gray).mean(axis=0)
    # return the result

haralick

array([ 9.59604364e-04,  1.70630329e+01,  9.94349378e-01,  1.50982635e+03,
        3.75619952e-01,  1.95857425e+02,  6.02224239e+03,  8.09156337e+00,
        1.08514499e+01,  7.03483840e-04,  2.97907773e+00, -4.70551661e-01,
        9.99302551e-01])

In [65]:
image = cv2.imread('cal3.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # compute the haralick texture feature vector
haralick = mahotas.features.haralick(gray).mean(axis=0)
    # return the result

haralick

array([ 3.99339824e-04,  3.42246906e+01,  9.95613244e-01,  3.90090204e+03,
        3.19670820e-01,  2.39850005e+02,  1.55693835e+04,  8.78134488e+00,
        1.18713848e+01,  5.58586838e-04,  3.25565548e+00, -4.75103624e-01,
        9.99675414e-01])

## Color

In [66]:
bins = 8 
image = cv2.imread('cal1.jpg')  
image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    # compute the color histogram 
hist  = cv2.calcHist([image], [0, 1, 2], None, [bins, bins, bins], [0, 256, 0, 256, 0, 256])
    # normalize the histogram
cv2.normalize(hist, hist)

hist.flatten()


array([4.03163023e-03, 5.93585128e-07, 0.00000000e+00, 4.09633107e-03,
       9.39348433e-03, 4.56526317e-03, 2.41250806e-02, 1.61591675e-02,
       6.63034560e-04, 1.28214393e-04, 8.72570148e-04, 4.72731190e-03,
       3.70337768e-03, 5.64143322e-02, 3.97256836e-02, 1.96832838e-03,
       5.82188275e-03, 9.32759698e-03, 5.38500445e-03, 9.43147391e-03,
       4.70089726e-02, 2.21137166e-01, 1.06899932e-01, 1.34031521e-02,
       2.71149678e-03, 1.64298434e-02, 1.95894968e-02, 3.29985842e-02,
       1.08124502e-01, 1.70692533e-01, 4.23273668e-02, 1.07082759e-03,
       1.57893650e-04, 1.93093240e-03, 1.31580019e-02, 3.35114412e-02,
       9.25571322e-02, 1.47844246e-02, 4.22157720e-03, 0.00000000e+00,
       1.12781172e-05, 1.06845328e-05, 1.43054014e-04, 2.04371358e-03,
       1.56528398e-03, 3.18161619e-04, 0.00000000e+00, 0.00000000e+00,
       5.93585128e-07, 0.00000000e+00, 2.25562344e-05, 4.27381310e-05,
       7.12302153e-06, 1.18717026e-06, 0.00000000e+00, 0.00000000e+00,
      

In [67]:
bins = 8 
image = cv2.imread('cal3.jpg')  
image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    # compute the color histogram 
hist  = cv2.calcHist([image], [0, 1, 2], None, [bins, bins, bins], [0, 256, 0, 256, 0, 256])
    # normalize the histogram
cv2.normalize(hist, hist)

hist.flatten()

array([1.92859297e-04, 1.44660417e-02, 2.80737802e-02, 2.84563098e-02,
       1.86324399e-03, 1.91265426e-04, 1.45839891e-04, 9.24449560e-05,
       5.25979922e-05, 4.13125344e-02, 6.44094273e-02, 5.85351884e-02,
       1.38029887e-03, 4.89320722e-04, 4.80554387e-04, 2.27924640e-04,
       5.33949315e-05, 1.43130298e-03, 2.89846817e-03, 1.69190206e-03,
       1.13962320e-04, 1.29901106e-04, 2.61396082e-04, 7.96939275e-07,
       4.30347209e-05, 4.38316602e-05, 8.68663774e-05, 3.98469638e-05,
       3.10806317e-05, 7.01306562e-05, 0.00000000e+00, 0.00000000e+00,
       3.18775710e-05, 1.35479677e-05, 4.22377816e-05, 1.59387855e-06,
       1.21134770e-04, 3.18775710e-06, 0.00000000e+00, 0.00000000e+00,
       2.31112390e-05, 4.78163565e-06, 1.51418462e-05, 2.39081783e-06,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.51418462e-05, 5.57857493e-06, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

## SVM

In [68]:
X = np.array([ctrnfeature,
             ctrnfeature1, otrnfeature, otrnfeature1, ctrnfeature2, 
             ctrnfeature3, otrnfeature2, otrnfeature3, ctrnfeature4, 
             ctrnfeature5, ctrnfeature6])
y = [0,0,1,1,0,0,1,1,0,0,0]
clf = svm.SVC(kernel='linear', C = 1.0) 

In [19]:
X = np.array([cmeans, cmeans1, cmeans2, cmeans3, cmeans4,
             cmeans5, cmeans6, cmeans7, omeans, omeans1, omeans2
             , omeans3])
y = [1,1,1,1,1,1,1,1,0,0,0,0]
clf = svm.SVC(kernel='linear', C = 1.0) 

In [20]:
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [70]:
print(clf.predict([ctstfeature]))
print(clf.predict([ctstfeature1]))
print(clf.predict([otstfeature]))
print(clf.predict([ctstfeature2]))

[0]
[0]
[0]
[0]


In [21]:
print(clf.predict([ctmeans]))
print(clf.predict([ctmeans1]))
print(clf.predict([otmeans]))

[1]
[1]
[0]


## ANN

In [71]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  ctrnfeature,
             ctrnfeature1, otrnfeature, otrnfeature1, ctrnfeature2, 
             ctrnfeature3, otrnfeature2, otrnfeature3, ctrnfeature4, 
             ctrnfeature5, ctrnfeature6 ])
    
# output dataset            
y = np.array([[0,0,1,1,0,0,1,1,0,0,0]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((7,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)


Output After Training:
[[0.49460571]
 [0.4963415 ]
 [0.4976181 ]
 [0.49757577]
 [0.49572928]
 [0.49477733]
 [0.4979136 ]
 [0.49785874]
 [0.49639949]
 [0.49695425]
 [0.49635479]]


## ANN pt. 2

In [22]:
#Independent variables
input_set = np.array([cmeans, cmeans1, cmeans2, cmeans3, cmeans4,
             cmeans5, cmeans6, cmeans7, omeans, omeans1, omeans2
             , omeans3])
#Dependent variable
labels = np.array([1,1,1,1,1,1,1,1,0,0,0,0])
labels = labels.reshape(12,1) #to convert labels to vector

In [170]:
#Independent variables
input_set = np.array([  ctrnfeature,
             ctrnfeature1, otrnfeature, otrnfeature1, ctrnfeature2, 
             ctrnfeature3, otrnfeature2, otrnfeature3, ctrnfeature4, 
             ctrnfeature5, ctrnfeature6 ])
#Dependent variable
labels = np.array([[0,0,1,1,0,0,1,1,0,0,0]])
labels = labels.reshape(11,1) #to convert labels to vector

ValueError: cannot reshape array of size 12 into shape (11,1)

In [23]:
np.random.seed(42)
weights = np.random.rand(3,1)
bias = np.random.rand(1)
lr = .05 #learning rate

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [24]:
for epoch in range(40000):
    inputs = input_set
    XW = np.dot(inputs, weights)+ bias
    z = sigmoid(XW)
    error = z - labels
    print(error.sum())
    dcost = error
    dpred = sigmoid_derivative(z)
    z_del = dcost * dpred
    inputs = input_set.T
    weights = weights - lr*np.dot(inputs, z_del)
    
    for num in z_del:
        bias = bias - lr*num

4.0
-8.0
4.0
-8.0
4.0
-8.0
4.0
-6.9999949415846565
4.0
2.5863166849623293e-14
2.5863166848482458e-14
2.586316684732977e-14
2.586316684618893e-14
2.586316684502457e-14
2.5863166843883737e-14
2.5863166842731138e-14
2.5863166841590297e-14
2.5863166840437705e-14
2.5863166839285103e-14
2.5863166838144262e-14
2.586316683699167e-14
2.5863166835839072e-14
2.586316683468638e-14
2.586316683354554e-14
2.5863166832404706e-14
2.5863166831252108e-14
2.586316683009951e-14
2.586316682894691e-14
2.5863166827806073e-14
2.5863166826665238e-14
2.5863166825500876e-14
2.586316682436004e-14
2.5863166823207443e-14
2.5863166822066513e-14
2.5863166820902155e-14
2.5863166819761314e-14
2.586316681862048e-14
2.586316681746788e-14
2.5863166816315282e-14
2.5863166815162687e-14
2.5863166814021846e-14
2.586316681288101e-14
2.5863166811716652e-14
2.5863166810575814e-14
2.5863166809423124e-14
2.586316680828229e-14
2.586316680712969e-14
2.5863166805977093e-14
2.5863166804836255e-14
2.5863166803683656e-14
2.58631668025428

C:\Users\njpel\.conda\envs\myenv2\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in exp
  import sys


2.586316566990658e-14
2.586316566875398e-14
2.5863165667601386e-14
2.5863165666460545e-14
2.5863165665307946e-14
2.5863165664155354e-14
2.5863165663014513e-14
2.5863165661861915e-14
2.5863165660721077e-14
2.586316565955672e-14
2.586316565841579e-14
2.5863165657274957e-14
2.5863165656110595e-14
2.5863165654969757e-14
2.5863165653805395e-14
2.586316565266456e-14
2.5863165651511962e-14
2.5863165650371127e-14
2.586316564921853e-14
2.5863165648065927e-14
2.5863165646925092e-14
2.58631656457724e-14
2.5863165644619807e-14
2.586316564346721e-14
2.5863165642326368e-14
2.5863165641185533e-14
2.5863165640021174e-14
2.5863165638880333e-14
2.5863165637727734e-14
2.58631656365869e-14
2.58631656354343e-14
2.5863165634281703e-14
2.5863165633140776e-14
2.5863165631988178e-14
2.586316563083558e-14
2.586316562968298e-14
2.5863165628542147e-14
2.5863165627401305e-14
2.586316562624871e-14
2.5863165625096112e-14
2.5863165623943513e-14
2.5863165622802672e-14
2.586316562166175e-14
2.5863165620497387e-14
2.586

2.586316518054265e-14
2.5863165179401808e-14
2.5863165178249216e-14
2.5863165177096614e-14
2.5863165175955776e-14
2.586316517480318e-14
2.586316517366234e-14
2.5863165172497984e-14
2.586316517135715e-14
2.5863165170204548e-14
2.586316516906371e-14
2.586316516791102e-14
2.5863165166758422e-14
2.5863165165617587e-14
2.586316516446499e-14
2.5863165163324154e-14
2.5863165162171555e-14
2.5863165161018954e-14
2.586316515987812e-14
2.586316515872552e-14
2.5863165157572922e-14
2.586316515642023e-14
2.5863165155279394e-14
2.586316515413856e-14
2.5863165152974194e-14
2.586316515183336e-14
2.586316515068076e-14
2.5863165149539926e-14
2.5863165148387328e-14
2.586316514723473e-14
2.586316514609389e-14
2.5863165144941293e-14
2.58631651437886e-14
2.5863165142636008e-14
2.5863165141495167e-14
2.5863165140354332e-14
2.5863165139201734e-14
2.5863165138037375e-14
2.5863165136884777e-14
2.5863165135743936e-14
2.58631651346031e-14
2.5863165133438745e-14
2.5863165132297904e-14
2.5863165131145214e-14
2.58631

2.5863164201838423e-14
2.5863164200697493e-14
2.5863164199556658e-14
2.5863164198392296e-14
2.586316419725146e-14
2.5863164196098863e-14
2.5863164194958025e-14
2.5863164193805427e-14
2.5863164192652828e-14
2.5863164191511994e-14
2.5863164190347632e-14
2.586316418919504e-14
2.5863164188042347e-14
2.586316418690151e-14
2.586316418576067e-14
2.5863164184608075e-14
2.5863164183455477e-14
2.586316418230288e-14
2.5863164181162044e-14
2.5863164180021203e-14
2.5863164178856847e-14
2.5863164177716006e-14
2.586316417656341e-14
2.586316417542248e-14
2.586316417425812e-14
2.5863164173117284e-14
2.586316417197645e-14
2.586316417082385e-14
2.5863164169671253e-14
2.5863164168518655e-14
2.5863164167377817e-14
2.586316416623698e-14
2.586316416507262e-14
2.5863164163931785e-14
2.5863164162779092e-14
2.5863164161638257e-14
2.5863164160473895e-14
2.586316415933306e-14
2.5863164158192225e-14
2.5863164157039624e-14
2.586316415589879e-14
2.5863164154734427e-14
2.5863164153593592e-14
2.5863164152452758e-14
2.

2.5863163054265475e-14
2.586316305312464e-14
2.5863163051983805e-14
2.5863163050819443e-14
2.586316304967861e-14
2.5863163048525915e-14
2.586316304738508e-14
2.5863163046220725e-14
2.5863163045079884e-14
2.586316304393905e-14
2.586316304278645e-14
2.586316304163385e-14
2.586316304048125e-14
2.5863163039340416e-14
2.586316303819958e-14
2.586316303703522e-14
2.586316303589429e-14
2.586316303474169e-14
2.5863163033600856e-14
2.58631630324365e-14
2.586316303129566e-14
2.5863163030154825e-14
2.5863163029002226e-14
2.586316302786139e-14
2.5863163026697027e-14
2.5863163025556192e-14
2.5863163024403505e-14
2.5863163023262664e-14
2.5863163022110065e-14
2.5863163020957473e-14
2.5863163019816632e-14
2.5863163018664034e-14
2.5863163017511436e-14
2.58631630163706e-14
2.5863163015218002e-14
2.5863163014077164e-14
2.5863163012912802e-14
2.586316301177188e-14
2.586316301061928e-14
2.586316300947844e-14
2.586316300832584e-14
2.586316300717325e-14
2.5863163006032408e-14
2.586316300487981e-14
2.586316300

2.5863161936566317e-14
2.586316193542548e-14
2.586316193427288e-14
2.5863161933120194e-14
2.5863161931967596e-14
2.5863161930826755e-14
2.586316192968592e-14
2.5863161928521564e-14
2.5863161927380723e-14
2.5863161926228125e-14
2.586316192508729e-14
2.586316192393469e-14
2.5863161922782093e-14
2.5863161921641164e-14
2.586316192048857e-14
2.586316191934773e-14
2.5863161918183375e-14
2.5863161917042534e-14
2.58631619159017e-14
2.58631619147491e-14
2.5863161913596502e-14
2.58631619124439e-14
2.5863161911303066e-14
2.5863161910150467e-14
2.586316190899778e-14
2.586316190785694e-14
2.586316190670434e-14
2.5863161905563506e-14
2.586316190439915e-14
2.586316190325831e-14
2.5863161902117475e-14
2.5863161900964876e-14
2.586316189982404e-14
2.586316189865968e-14
2.5863161897518845e-14
2.5863161896366152e-14
2.5863161895225317e-14
2.586316189407272e-14
2.586316189292012e-14
2.5863161891779285e-14
2.5863161890626687e-14
2.5863161889474085e-14
2.586316188833325e-14
2.5863161887180652e-14
2.586316188

2.5863160940643536e-14
2.5863160939490937e-14
2.586316093833834e-14
2.5863160937197504e-14
2.5863160936044906e-14
2.5863160934892307e-14
2.5863160933751472e-14
2.5863160932598874e-14
2.586316093145804e-14
2.5863160930293677e-14
2.5863160929152842e-14
2.586316092800015e-14
2.5863160926859315e-14
2.5863160925706716e-14
2.5863160924554118e-14
2.5863160923413283e-14
2.5863160922260685e-14
2.586316092111985e-14
2.586316091996725e-14
2.5863160918814653e-14
2.5863160917673818e-14
2.5863160916521125e-14
2.5863160915368527e-14
2.586316091421593e-14
2.586316091306333e-14
2.5863160911922495e-14
2.5863160910758137e-14
2.58631609096173e-14
2.58631609084647e-14
2.5863160907323865e-14
2.5863160906171267e-14
2.586316090501867e-14
2.586316090387774e-14
2.586316090272514e-14
2.5863160901572542e-14
2.5863160900419944e-14
2.586316089927911e-14
2.586316089813827e-14
2.5863160896985673e-14
2.5863160895833074e-14
2.5863160894680476e-14
2.586316089353964e-14
2.5863160892398712e-14
2.5863160891234353e-14
2.586

2.5863160481141667e-14
2.5863160480000832e-14
2.5863160478848233e-14
2.5863160477707392e-14
2.5863160476543037e-14
2.5863160475402107e-14
2.5863160474261272e-14
2.5863160473108674e-14
2.5863160471956076e-14
2.5863160470803477e-14
2.5863160469662642e-14
2.5863160468510044e-14
2.5863160467357446e-14
2.5863160466216604e-14
2.5863160465064006e-14
2.586316046392317e-14
2.586316046275872e-14
2.5863160461617886e-14
2.5863160460477045e-14
2.5863160459324447e-14
2.5863160458171855e-14
2.5863160457019256e-14
2.5863160455878415e-14
2.5863160454725817e-14
2.5863160453584982e-14
2.5863160452432383e-14
2.5863160451279697e-14
2.5863160450138856e-14
2.5863160448986257e-14
2.586316044783366e-14
2.5863160446692824e-14
2.5863160445540226e-14
2.586316044439939e-14
2.586316044323503e-14
2.5863160442094194e-14
2.5863160440941596e-14
2.586316043980076e-14
2.5863160438648068e-14
2.586316043749547e-14
2.5863160436354635e-14
2.5863160435202036e-14
2.5863160434049438e-14
2.5863160432908603e-14
2.5863160431756005

2.5863159581708684e-14
2.586315958055599e-14
2.5863159579403393e-14
2.5863159578262558e-14
2.586315957710996e-14
2.586315957595736e-14
2.5863159574816526e-14
2.5863159573663928e-14
2.586315957252309e-14
2.5863159571370492e-14
2.5863159570217893e-14
2.5863159569076967e-14
2.586315956792437e-14
2.586315956678353e-14
2.5863159565619172e-14
2.5863159564478334e-14
2.586315956332574e-14
2.58631595621849e-14
2.5863159561032302e-14
2.5863159559879704e-14
2.586315955873887e-14
2.586315955758627e-14
2.5863159556433584e-14
2.5863159555292743e-14
2.5863159554140144e-14
2.586315955299931e-14
2.5863159551834948e-14
2.5863159550694113e-14
2.5863159549541514e-14
2.586315954840068e-14
2.586315954724808e-14
2.5863159546095483e-14
2.5863159544954648e-14
2.5863159543801955e-14
2.586315954266112e-14
2.5863159541496758e-14
2.5863159540355923e-14
2.586315953921509e-14
2.586315953806249e-14
2.5863159536909892e-14
2.5863159535757294e-14
2.586315953461646e-14
2.586315953346386e-14
2.58631595322995e-14
2.5863159

2.5863158461704384e-14
2.586315846056355e-14
2.586315845941095e-14
2.5863158458270115e-14
2.5863158457105754e-14
2.586315845596492e-14
2.586315845481232e-14
2.586315845367139e-14
2.5863158452518793e-14
2.5863158451366194e-14
2.586315845022536e-14
2.586315844907276e-14
2.5863158447920163e-14
2.5863158446779328e-14
2.586315844562673e-14
2.5863158444485888e-14
2.5863158443321533e-14
2.5863158442180698e-14
2.5863158441028005e-14
2.586315843988717e-14
2.5863158438746332e-14
2.5863158437581976e-14
2.5863158436441135e-14
2.5863158435288537e-14
2.5863158434147702e-14
2.5863158432995104e-14
2.5863158431842505e-14
2.586315843070167e-14
2.5863158429549072e-14
2.586315842839638e-14
2.5863158427243787e-14
2.5863158426102946e-14
2.586315842496211e-14
2.586315842379775e-14
2.5863158422656914e-14
2.586315842150432e-14
2.586315842036348e-14
2.5863158419222643e-14
2.5863158418058287e-14
2.5863158416917358e-14
2.586315841576476e-14
2.5863158414623925e-14
2.5863158413459563e-14
2.5863158412306964e-14
2.58

2.5863157540430736e-14
2.5863157539289895e-14
2.5863157538137297e-14
2.5863157536984698e-14
2.5863157535832103e-14
2.5863157534691174e-14
2.586315753355034e-14
2.586315753239774e-14
2.5863157531245142e-14
2.5863157530092544e-14
2.586315752895171e-14
2.5863157527810874e-14
2.5863157526646512e-14
2.5863157525505677e-14
2.586315752435308e-14
2.586315752321224e-14
2.586315752204779e-14
2.5863157520906956e-14
2.586315751976612e-14
2.5863157518613523e-14
2.5863157517460924e-14
2.5863157516308326e-14
2.5863157515167485e-14
2.586315751402665e-14
2.5863157512862288e-14
2.5863157511721453e-14
2.5863157510568766e-14
2.5863157509427928e-14
2.586315750827533e-14
2.5863157507122732e-14
2.5863157505981897e-14
2.5863157504829298e-14
2.5863157503688464e-14
2.5863157502524102e-14
2.5863157501383267e-14
2.5863157500242426e-14
2.5863157499089827e-14
2.586315749793714e-14
2.5863157496784542e-14
2.5863157495643707e-14
2.5863157494491112e-14
2.5863157493338514e-14
2.5863157492197673e-14
2.586315749104508e-14

2.5863156369900037e-14
2.5863156368747438e-14
2.5863156367606597e-14
2.5863156366454e-14
2.58631563653014e-14
2.5863156364160565e-14
2.5863156363007967e-14
2.5863156361867132e-14
2.5863156360702774e-14
2.586315635956194e-14
2.5863156358409246e-14
2.586315635726841e-14
2.5863156356127576e-14
2.5863156354963214e-14
2.586315635382238e-14
2.586315635266978e-14
2.5863156351528943e-14
2.5863156350376344e-14
2.5863156349223752e-14
2.586315634808291e-14
2.5863156346930313e-14
2.5863156345777626e-14
2.5863156344625028e-14
2.586315634347243e-14
2.586315634233159e-14
2.5863156341167236e-14
2.58631563400264e-14
2.5863156338873803e-14
2.586315633773296e-14
2.5863156336580363e-14
2.5863156335427765e-14
2.586315633428684e-14
2.586315633313424e-14
2.5863156331993405e-14
2.5863156330829043e-14
2.586315632968821e-14
2.5863156328547374e-14
2.5863156327394775e-14
2.5863156326242177e-14
2.586315632508958e-14
2.5863156323948744e-14
2.5863156322807906e-14
2.5863156321643455e-14
2.586315632050262e-14
2.586315

2.5863155699047885e-14
2.586315569789529e-14
2.586315569675436e-14
2.5863155695601762e-14
2.586315569444917e-14
2.586315569330833e-14
2.586315569215573e-14
2.5863155691014896e-14
2.5863155689850534e-14
2.5863155688709702e-14
2.5863155687568868e-14
2.586315568641627e-14
2.586315568526367e-14
2.5863155684110978e-14
2.5863155682970143e-14
2.5863155681829305e-14
2.5863155680664946e-14
2.5863155679524108e-14
2.586315567837151e-14
2.5863155677230675e-14
2.586315567606632e-14
2.5863155674925478e-14
2.5863155673784643e-14
2.5863155672631954e-14
2.586315567149112e-14
2.5863155670326757e-14
2.5863155669185922e-14
2.5863155668045087e-14
2.586315566689249e-14
2.586315566573989e-14
2.5863155664587295e-14
2.5863155663446454e-14
2.5863155662293856e-14
2.5863155661141257e-14
2.5863155660000334e-14
2.5863155658847736e-14
2.5863155657706898e-14
2.586315565654254e-14
2.58631556554017e-14
2.5863155654260866e-14
2.5863155653096504e-14
2.5863155651943906e-14
2.5863155650791308e-14
2.5863155649650473e-14
2.5

2.586315469620976e-14
2.5863154695068925e-14
2.5863154693916327e-14
2.586315469276373e-14
2.5863154691622802e-14
2.5863154690470203e-14
2.586315468932937e-14
2.586315468817677e-14
2.5863154687024172e-14
2.586315468588334e-14
2.5863154684730742e-14
2.58631546835899e-14
2.5863154682425545e-14
2.5863154681284704e-14
2.586315468013211e-14
2.586315467899118e-14
2.586315467783858e-14
2.5863154676685982e-14
2.5863154675545148e-14
2.586315467439255e-14
2.5863154673239954e-14
2.586315467209912e-14
2.586315467094652e-14
2.586315466980568e-14
2.5863154668641324e-14
2.5863154667500395e-14
2.58631546663478e-14
2.5863154665206965e-14
2.5863154664066123e-14
2.5863154662901768e-14
2.5863154661760927e-14
2.586315466060833e-14
2.5863154659467497e-14
2.5863154658314898e-14
2.58631546571623e-14
2.5863154656021465e-14
2.5863154654868772e-14
2.5863154653716177e-14
2.5863154652563578e-14
2.5863154651422744e-14
2.5863154650281902e-14
2.5863154649117547e-14
2.586315464797671e-14
2.586315464682411e-14
2.5863154

2.5863153903604703e-14
2.5863153902463862e-14
2.5863153901299506e-14
2.5863153900158668e-14
2.5863153899017833e-14
2.5863153897865235e-14
2.5863153896712637e-14
2.5863153895559947e-14
2.5863153894419112e-14
2.5863153893266514e-14
2.5863153892113915e-14
2.586315389097308e-14
2.5863153889820482e-14
2.5863153888679644e-14
2.5863153887515288e-14
2.5863153886374447e-14
2.5863153885233612e-14
2.5863153884081014e-14
2.5863153882928324e-14
2.5863153881775726e-14
2.586315388063489e-14
2.5863153879482293e-14
2.5863153878341458e-14
2.5863153877188863e-14
2.5863153876036264e-14
2.5863153874895423e-14
2.5863153873742825e-14
2.586315387259023e-14
2.586315387143763e-14
2.58631538702967e-14
2.5863153869155867e-14
2.5863153867991505e-14
2.5863153866850673e-14
2.5863153865698075e-14
2.586315386455724e-14
2.586315386340464e-14
2.5863153862252043e-14
2.5863153861111205e-14
2.5863153859958607e-14
2.586315385880592e-14
2.5863153857653322e-14
2.5863153856512487e-14
2.586315385537165e-14
2.586315385421905e-14

2.5863153160397072e-14
2.5863153159244473e-14
2.5863153158091875e-14
2.586315315695104e-14
2.5863153155798442e-14
2.5863153154645846e-14
2.5863153153493248e-14
2.586315315234065e-14
2.586315315119981e-14
2.5863153150035453e-14
2.586315314889462e-14
2.5863153147741928e-14
2.5863153146601093e-14
2.5863153145460255e-14
2.5863153144295897e-14
2.586315314315506e-14
2.586315314200246e-14
2.5863153140861625e-14
2.5863153139709027e-14
2.5863153138556432e-14
2.586315313741559e-14
2.5863153136263e-14
2.5863153135110306e-14
2.586315313395771e-14
2.5863153132816876e-14
2.5863153131676034e-14
2.586315313051168e-14
2.586315312937084e-14
2.5863153128218243e-14
2.5863153127077408e-14
2.586315312592481e-14
2.586315312477221e-14
2.5863153123631285e-14
2.5863153122478686e-14
2.5863153121326088e-14
2.586315312017349e-14
2.5863153119032655e-14
2.5863153117891817e-14
2.5863153116739218e-14
2.586315311558662e-14
2.586315311443402e-14
2.586315311329319e-14
2.586315311214059e-14
2.58631531109879e-14
2.58631531

2.5863152465410844e-14
2.5863152464270006e-14
2.5863152463117408e-14
2.586315246196472e-14
2.5863152460812123e-14
2.5863152459659528e-14
2.5863152458518687e-14
2.5863152457366088e-14
2.5863152456225253e-14
2.5863152455072658e-14
2.586315245392006e-14
2.586315245277922e-14
2.5863152451626623e-14
2.5863152450474025e-14
2.5863152449333096e-14
2.5863152448180504e-14
2.5863152447039666e-14
2.586315244587531e-14
2.586315244473447e-14
2.586315244358187e-14
2.5863152442441036e-14
2.586315244128844e-14
2.5863152440135842e-14
2.5863152438995e-14
2.5863152437842314e-14
2.586315243668972e-14
2.5863152435548878e-14
2.586315243439628e-14
2.5863152433255445e-14
2.586315243210285e-14
2.586315243095025e-14
2.5863152429797653e-14
2.5863152428656818e-14
2.586315242751598e-14
2.5863152426351624e-14
2.5863152425210695e-14
2.5863152424058096e-14
2.5863152422917258e-14
2.586315242176466e-14
2.586315242061206e-14
2.5863152419471227e-14
2.586315241831863e-14
2.5863152417166033e-14
2.5863152416013435e-14
2.5863

2.586315162800707e-14
2.5863151626854473e-14
2.5863151625701874e-14
2.5863151624561043e-14
2.5863151623408444e-14
2.5863151622267603e-14
2.5863151621115008e-14
2.586315161996241e-14
2.5863151618821575e-14
2.5863151617668976e-14
2.5863151616516286e-14
2.5863151615363688e-14
2.5863151614222853e-14
2.5863151613082018e-14
2.586315161191766e-14
2.5863151610776825e-14
2.5863151609624226e-14
2.5863151608483388e-14
2.586315160733079e-14
2.5863151606178192e-14
2.5863151605037357e-14
2.5863151603884667e-14
2.586315160273207e-14
2.5863151601567713e-14
2.5863151600426872e-14
2.586315159928604e-14
2.5863151598133442e-14
2.5863151596980843e-14
2.5863151595828245e-14
2.5863151594687407e-14
2.586315159353481e-14
2.586315159238221e-14
2.5863151591241284e-14
2.5863151590088692e-14
2.586315158894785e-14
2.5863151587783495e-14
2.5863151586642657e-14
2.5863151585501822e-14
2.5863151584349224e-14
2.5863151583196626e-14
2.586315158204403e-14
2.586315158090319e-14
2.5863151579750503e-14
2.5863151578597904e-14

2.58631510008129e-14
2.58631509996603e-14
2.5863150998507703e-14
2.5863150997355104e-14
2.586315099620251e-14
2.586315099504991e-14
2.586315099390907e-14
2.5863150992756474e-14
2.5863150991615545e-14
2.586315099045119e-14
2.586315098931035e-14
2.5863150988157753e-14
2.5863150987016918e-14
2.586315098586432e-14
2.5863150984711725e-14
2.586315098357089e-14
2.586315098241829e-14
2.5863150981277453e-14
2.5863150980124855e-14
2.5863150978972168e-14
2.586315097783133e-14
2.5863150976678732e-14
2.5863150975526134e-14
2.5863150974373535e-14
2.5863150973232704e-14
2.5863150972091862e-14
2.5863150970927507e-14
2.586315096978667e-14
2.586315096863407e-14
2.586315096749314e-14
2.5863150966340543e-14
2.5863150965187947e-14
2.5863150964047112e-14
2.5863150962894514e-14
2.586315096175368e-14
2.586315096058932e-14
2.5863150959448486e-14
2.5863150958307645e-14
2.586315095715505e-14
2.586315095600245e-14
2.5863150954849764e-14
2.5863150953708926e-14
2.586315095256809e-14
2.586315095140373e-14
2.58631509

2.5863149852076177e-14
2.5863149850935342e-14
2.5863149849794507e-14
2.5863149848641912e-14
2.5863149847489314e-14
2.5863149846336715e-14
2.5863149845195877e-14
2.5863149844055042e-14
2.5863149842890684e-14
2.586314984174985e-14
2.586314984059725e-14
2.586314983945632e-14
2.5863149838291962e-14
2.5863149837151127e-14
2.586314983601029e-14
2.586314983485769e-14
2.5863149833705093e-14
2.5863149832552497e-14
2.5863149831411662e-14
2.586314983027082e-14
2.5863149829118226e-14
2.5863149827965628e-14
2.586314982681294e-14
2.5863149825672103e-14
2.5863149824519505e-14
2.5863149823366906e-14
2.586314982222607e-14
2.5863149821073476e-14
2.5863149819932635e-14
2.586314981876828e-14
2.586314981762744e-14
2.5863149816486607e-14
2.5863149815333917e-14
2.5863149814181318e-14
2.586314981302872e-14
2.5863149811887885e-14
2.586314981073529e-14
2.5863149809582692e-14
2.5863149808441857e-14
2.586314980728926e-14
2.586314980614842e-14
2.5863149804995822e-14
2.5863149803843227e-14
2.5863149802702297e-14
2.

2.5863148984798957e-14
2.586314898365812e-14
2.5863148982505432e-14
2.5863148981364594e-14
2.5863148980211996e-14
2.5863148979059398e-14
2.5863148977918566e-14
2.5863148976765968e-14
2.586314897561337e-14
2.5863148974460774e-14
2.5863148973319933e-14
2.5863148972179098e-14
2.5863148971026503e-14
2.586314896987381e-14
2.5863148968721215e-14
2.586314896758038e-14
2.586314896643954e-14
2.5863148965275183e-14
2.5863148964134345e-14
2.5863148962981747e-14
2.5863148961840915e-14
2.5863148960676553e-14
2.5863148959535718e-14
2.586314895839488e-14
2.5863148957242194e-14
2.5863148956089595e-14
2.5863148954937e-14
2.586314895379616e-14
2.5863148952655327e-14
2.5863148951490965e-14
2.586314895035013e-14
2.5863148949197532e-14
2.5863148948056694e-14
2.5863148946904096e-14
2.58631489457515e-14
2.586314894461057e-14
2.5863148943457973e-14
2.586314894231714e-14
2.586314894115278e-14
2.5863148940011944e-14
2.5863148938871106e-14
2.5863148937718508e-14
2.5863148936565913e-14
2.5863148935413314e-14
2.58

2.5863148340386268e-14
2.586314833923367e-14
2.5863148338081075e-14
2.586314833694024e-14
2.586314833578764e-14
2.5863148334646803e-14
2.5863148333494205e-14
2.5863148332341515e-14
2.586314833120068e-14
2.5863148330048082e-14
2.5863148328895487e-14
2.5863148327742888e-14
2.5863148326602054e-14
2.5863148325461216e-14
2.5863148324285096e-14
2.5863148323144255e-14
2.586314832199166e-14
2.586314832085073e-14
2.5863148319686375e-14
2.5863148318545537e-14
2.5863148317404702e-14
2.5863148316252107e-14
2.586314831509951e-14
2.586314831394691e-14
2.586314831280608e-14
2.5863148311665237e-14
2.586314831051264e-14
2.5863148309360044e-14
2.586314830820735e-14
2.586314830706652e-14
2.586314830591392e-14
2.5863148304761322e-14
2.586314830362049e-14
2.5863148302467886e-14
2.586314830132705e-14
2.5863148300162692e-14
2.5863148299021858e-14
2.5863148297881023e-14
2.5863148296728427e-14
2.5863148295575734e-14
2.586314829442314e-14
2.5863148293282304e-14
2.5863148292129706e-14
2.5863148290977105e-14
2.58

2.5863147556955225e-14
2.586314755581439e-14
2.5863147554661795e-14
2.5863147553509197e-14
2.586314755236836e-14
2.586314755121576e-14
2.5863147550074925e-14
2.5863147548910567e-14
2.586314754775788e-14
2.5863147546605282e-14
2.5863147545464444e-14
2.586314754432361e-14
2.586314754315925e-14
2.5863147542018415e-14
2.5863147540865817e-14
2.586314753972498e-14
2.586314753857238e-14
2.5863147537419785e-14
2.5863147536278856e-14
2.5863147535126257e-14
2.5863147533973662e-14
2.5863147532821064e-14
2.586314753168023e-14
2.586314753053939e-14
2.5863147529375035e-14
2.5863147528234197e-14
2.58631475270816e-14
2.5863147525940764e-14
2.5863147524799926e-14
2.5863147523635476e-14
2.5863147522494644e-14
2.5863147521342046e-14
2.5863147520201208e-14
2.5863147519036846e-14
2.586314751789601e-14
2.586314751675518e-14
2.586314751560258e-14
2.5863147514449983e-14
2.5863147513297388e-14
2.5863147512156458e-14
2.586314751101562e-14
2.5863147509851258e-14
2.5863147508710426e-14
2.5863147507557828e-14
2.58

2.58631464610857e-14
2.5863146459933103e-14
2.5863146458780504e-14
2.5863146457639578e-14
2.586314645648698e-14
2.5863146455346148e-14
2.5863146454181786e-14
2.586314645304095e-14
2.5863146451900113e-14
2.5863146450747515e-14
2.586314644959492e-14
2.586314644844232e-14
2.5863146447301486e-14
2.586314644614889e-14
2.5863146445007962e-14
2.5863146443855366e-14
2.5863146442702768e-14
2.586314644156193e-14
2.5863146440409332e-14
2.5863146439256736e-14
2.5863146438115902e-14
2.5863146436963303e-14
2.5863146435822465e-14
2.586314643465811e-14
2.5863146433517183e-14
2.5863146432364585e-14
2.5863146431223747e-14
2.586314643007115e-14
2.586314642891855e-14
2.5863146427765955e-14
2.5863146426613357e-14
2.586314642546076e-14
2.586314642431992e-14
2.5863146423167325e-14
2.586314642202649e-14
2.58631464208738e-14
2.5863146419721202e-14
2.5863146418568604e-14
2.5863146417427772e-14
2.586314641628693e-14
2.5863146415122575e-14
2.5863146413981737e-14
2.5863146412829142e-14
2.5863146411688307e-14
2.586

2.5863145473184748e-14
2.586314547203215e-14
2.5863145470879554e-14
2.5863145469738713e-14
2.5863145468586118e-14
2.5863145467445283e-14
2.5863145466292685e-14
2.5863145465139995e-14
2.58631454639874e-14
2.5863145462846565e-14
2.5863145461705727e-14
2.586314546054137e-14
2.586314545940053e-14
2.5863145458247935e-14
2.58631454571071e-14
2.5863145455954505e-14
2.5863145454801907e-14
2.5863145453660974e-14
2.5863145452508376e-14
2.586314545135578e-14
2.5863145450203182e-14
2.5863145449062347e-14
2.586314544792151e-14
2.5863145446757154e-14
2.5863145445616316e-14
2.5863145444463717e-14
2.5863145443322885e-14
2.5863145442170287e-14
2.5863145441017597e-14
2.5863145439876762e-14
2.5863145438724167e-14
2.5863145437583326e-14
2.586314543641897e-14
2.5863145435278132e-14
2.5863145434137298e-14
2.5863145432984702e-14
2.5863145431832104e-14
2.586314543067951e-14
2.5863145429538668e-14
2.586314542839774e-14
2.586314542723338e-14
2.5863145426092548e-14
2.586314542493995e-14
2.586314542379911e-14
2.5

2.58631447759052e-14
2.5863144774764363e-14
2.5863144773623528e-14
2.5863144772470933e-14
2.5863144771318335e-14
2.586314477016574e-14
2.58631447690249e-14
2.5863144767872303e-14
2.586314476671961e-14
2.586314476557878e-14
2.586314476442618e-14
2.5863144763285342e-14
2.5863144762120987e-14
2.586314476098015e-14
2.5863144759839314e-14
2.586314475868672e-14
2.586314475753412e-14
2.5863144756381522e-14
2.5863144755240684e-14
2.5863144754087997e-14
2.586314475294716e-14
2.5863144751794564e-14
2.5863144750641966e-14
2.586314474950113e-14
2.5863144748348535e-14
2.5863144747195937e-14
2.58631447460551e-14
2.58631447449025e-14
2.586314474376167e-14
2.5863144742597212e-14
2.586314474145638e-14
2.5863144740303782e-14
2.5863144739162944e-14
2.5863144738010346e-14
2.586314473685775e-14
2.5863144735716916e-14
2.586314473456432e-14
2.5863144733411722e-14
2.5863144732259127e-14
2.5863144731118286e-14
2.586314472997736e-14
2.586314472882476e-14
2.5863144727672166e-14
2.5863144726519568e-14
2.586314472

2.586314390059516e-14
2.586314389944256e-14
2.5863143898289966e-14
2.5863143897149036e-14
2.5863143896008198e-14
2.58631438948556e-14
2.5863143893703005e-14
2.5863143892550406e-14
2.5863143891409575e-14
2.5863143890256976e-14
2.586314388910438e-14
2.586314388796354e-14
2.5863143886810945e-14
2.586314388567011e-14
2.5863143884505656e-14
2.5863143883364822e-14
2.5863143882223984e-14
2.5863143881071388e-14
2.586314387991879e-14
2.5863143878766192e-14
2.586314387762536e-14
2.5863143876472762e-14
2.5863143875320166e-14
2.5863143874179328e-14
2.586314387302673e-14
2.5863143871885804e-14
2.5863143870733205e-14
2.5863143869580607e-14
2.5863143868439775e-14
2.5863143867287174e-14
2.586314386614634e-14
2.586314386498198e-14
2.5863143863841145e-14
2.5863143862688547e-14
2.586314386154771e-14
2.5863143860395025e-14
2.5863143859242427e-14
2.586314385810159e-14
2.586314385694899e-14
2.5863143855796395e-14
2.5863143854643797e-14
2.5863143853502965e-14
2.5863143852362124e-14
2.5863143851197766e-14
2.5

2.5863143298664407e-14
2.5863143297523565e-14
2.5863143296370882e-14
2.586314329521828e-14
2.5863143294077446e-14
2.586314329292485e-14
2.5863143291772252e-14
2.5863143290619654e-14
2.5863143289478816e-14
2.5863143288337984e-14
2.5863143287173622e-14
2.586314328603279e-14
2.5863143284880192e-14
2.5863143283739266e-14
2.5863143282598424e-14
2.5863143281434072e-14
2.586314328029323e-14
2.5863143279140636e-14
2.58631432779998e-14
2.5863143276835442e-14
2.5863143275694604e-14
2.586314327455377e-14
2.586314327340117e-14
2.586314327224848e-14
2.5863143271095886e-14
2.586314326995505e-14
2.5863143268814213e-14
2.5863143267649857e-14
2.586314326650902e-14
2.586314326535642e-14
2.586314326421559e-14
2.5863143263051227e-14
2.586314326191039e-14
2.5863143260769555e-14
2.5863143259616865e-14
2.586314325846427e-14
2.586314325731167e-14
2.5863143256170836e-14
2.5863143255029998e-14
2.5863143253877403e-14
2.5863143252724805e-14
2.586314325157221e-14
2.5863143250431375e-14
2.5863143249278773e-14
2.586

2.5863142545107135e-14
2.586314254395454e-14
2.58631425428137e-14
2.5863142541661103e-14
2.586314254052027e-14
2.586314253935591e-14
2.5863142538215078e-14
2.5863142537074148e-14
2.5863142535921553e-14
2.5863142534768952e-14
2.5863142533616353e-14
2.5863142532475522e-14
2.5863142531322923e-14
2.5863142530170328e-14
2.5863142529029487e-14
2.5863142527876892e-14
2.5863142526736057e-14
2.5863142525571698e-14
2.586314252443077e-14
2.5863142523289937e-14
2.5863142522137335e-14
2.58631425209965e-14
2.5863142519832142e-14
2.5863142518691307e-14
2.5863142517538712e-14
2.586314251639787e-14
2.5863142515245275e-14
2.5863142514092677e-14
2.586314251295175e-14
2.5863142511799155e-14
2.5863142510646557e-14
2.5863142509505722e-14
2.586314250835312e-14
2.586314250721229e-14
2.5863142506047927e-14
2.5863142504907095e-14
2.5863142503754497e-14
2.586314250261366e-14
2.5863142501461064e-14
2.5863142500308377e-14
2.586314249916754e-14
2.586314249801494e-14
2.586314249687411e-14
2.5863142495721504e-14
2.58

2.5863141882311768e-14
2.5863141881159173e-14
2.5863141880018332e-14
2.586314187885398e-14
2.586314187771314e-14
2.5863141876560543e-14
2.5863141875419617e-14
2.586314187426702e-14
2.5863141873114423e-14
2.5863141871973582e-14
2.5863141870820987e-14
2.586314186966839e-14
2.5863141868527557e-14
2.586314186737496e-14
2.586314186623412e-14
2.5863141865069765e-14
2.5863141863928927e-14
2.5863141862776237e-14
2.5863141861635402e-14
2.5863141860482807e-14
2.586314185933021e-14
2.5863141858177613e-14
2.5863141857025015e-14
2.5863141855884177e-14
2.5863141854731582e-14
2.5863141853578984e-14
2.5863141852438146e-14
2.586314185128546e-14
2.5863141850132864e-14
2.5863141848980265e-14
2.5863141847839427e-14
2.5863141846698596e-14
2.5863141845534234e-14
2.5863141844393402e-14
2.58631418432408e-14
2.5863141842099966e-14
2.586314184094737e-14
2.5863141839794772e-14
2.5863141838653846e-14
2.5863141837501247e-14
2.5863141836348652e-14
2.5863141835196054e-14
2.5863141834055216e-14
2.5863141832914384e-14

2.586314104145055e-14
2.5863141040297952e-14
2.586314103914535e-14
2.586314103800452e-14
2.586314103685192e-14
2.5863141035699325e-14
2.5863141034546727e-14
2.586314103340589e-14
2.5863141032265057e-14
2.5863141031100695e-14
2.586314102995977e-14
2.586314102880717e-14
2.5863141027666332e-14
2.5863141026513737e-14
2.586314102536114e-14
2.5863141024220307e-14
2.586314102306771e-14
2.586314102192687e-14
2.5863141020762515e-14
2.5863141019621677e-14
2.5863141018480845e-14
2.5863141017328156e-14
2.5863141016175557e-14
2.5863141015022962e-14
2.586314101388212e-14
2.5863141012729526e-14
2.5863141011576927e-14
2.5863141010436096e-14
2.5863141009283494e-14
2.586314100814266e-14
2.58631410069783e-14
2.5863141005837466e-14
2.586314100469654e-14
2.5863141003543944e-14
2.5863141002391346e-14
2.586314100123875e-14
2.5863141000097912e-14
2.5863140998945314e-14
2.5863140997804476e-14
2.5863140996651878e-14
2.5863140995487525e-14
2.5863140994346687e-14
2.5863140993194e-14
2.58631409920414e-14
2.5863140

2.5863140185652636e-14
2.5863140184499952e-14
2.586314018335911e-14
2.5863140182206516e-14
2.586314018105392e-14
2.5863140179913086e-14
2.5863140178760484e-14
2.586314017760789e-14
2.5863140176467054e-14
2.586314017531446e-14
2.5863140174173618e-14
2.5863140173009265e-14
2.5863140171868336e-14
2.5863140170715734e-14
2.5863140169574903e-14
2.5863140168434065e-14
2.586314016726971e-14
2.586314016612887e-14
2.5863140164976273e-14
2.586314016383544e-14
2.5863140162682843e-14
2.586314016153024e-14
2.5863140160389315e-14
2.586314015923672e-14
2.586314015808412e-14
2.5863140156931526e-14
2.586314015579069e-14
2.5863140154649853e-14
2.5863140153485494e-14
2.586314015234466e-14
2.5863140151192064e-14
2.5863140150051226e-14
2.586314014888687e-14
2.5863140147745944e-14
2.5863140146605103e-14
2.5863140145452508e-14
2.5863140144299913e-14
2.5863140143147314e-14
2.5863140142006476e-14
2.586314014086564e-14
2.5863140139713046e-14
2.586314013856045e-14
2.5863140137407853e-14
2.5863140136267015e-14
2.5

2.5863139521692882e-14
2.586313952054028e-14
2.586313951939945e-14
2.586313951824685e-14
2.5863139517094255e-14
2.586313951594166e-14
2.586313951480082e-14
2.5863139513659987e-14
2.586313951249563e-14
2.5863139511354787e-14
2.5863139510202104e-14
2.5863139509061266e-14
2.5863139507908668e-14
2.5863139506756072e-14
2.5863139505615237e-14
2.5863139504462636e-14
2.5863139503321804e-14
2.5863139502157446e-14
2.586313950101661e-14
2.5863139499875773e-14
2.5863139498723086e-14
2.5863139497570484e-14
2.586313949641789e-14
2.5863139495277054e-14
2.586313949412446e-14
2.5863139492971864e-14
2.5863139491831023e-14
2.5863139490678428e-14
2.5863139489537596e-14
2.5863139488373234e-14
2.5863139487232396e-14
2.586313948609147e-14
2.586313948493887e-14
2.5863139483786276e-14
2.586313948263368e-14
2.5863139481492846e-14
2.5863139480340245e-14
2.586313947919941e-14
2.5863139478046814e-14
2.586313947689422e-14
2.586313947575338e-14
2.5863139474600783e-14
2.5863139473448093e-14
2.5863139472307258e-14
2.5

2.5863138372980286e-14
2.586313837183945e-14
2.586313837068676e-14
2.5863138369534166e-14
2.5863138368381568e-14
2.586313836724073e-14
2.5863138366088135e-14
2.5863138364935536e-14
2.5863138363794704e-14
2.586313836264211e-14
2.5863138361501268e-14
2.586313836033691e-14
2.5863138359196078e-14
2.5863138358055148e-14
2.5863138356902553e-14
2.586313835574995e-14
2.5863138354597356e-14
2.586313835345652e-14
2.5863138352303926e-14
2.5863138351163088e-14
2.586313835001049e-14
2.5863138348857895e-14
2.586313834771706e-14
2.586313834656437e-14
2.5863138345411775e-14
2.5863138344270937e-14
2.5863138343118338e-14
2.5863138341977507e-14
2.5863138340813148e-14
2.586313833967231e-14
2.586313833851971e-14
2.586313833737888e-14
2.586313833622628e-14
2.5863138335073686e-14
2.5863138333932754e-14
2.5863138332780158e-14
2.586313833162756e-14
2.5863138330486728e-14
2.586313832933413e-14
2.5863138328193292e-14
2.5863138327040697e-14
2.58631383258881e-14
2.5863138324735503e-14
2.5863138323594665e-14
2.5863

2.586313779977068e-14
2.586313779861808e-14
2.5863137797477248e-14
2.5863137796312886e-14
2.586313779517196e-14
2.5863137794031128e-14
2.5863137792878526e-14
2.5863137791725928e-14
2.5863137790573333e-14
2.5863137789432498e-14
2.5863137788279903e-14
2.5863137787139065e-14
2.586313778598647e-14
2.586313778483387e-14
2.5863137783693033e-14
2.586313778254035e-14
2.586313778138775e-14
2.5863137780246913e-14
2.5863137779094318e-14
2.586313777795348e-14
2.5863137776789124e-14
2.5863137775648286e-14
2.586313777449569e-14
2.5863137773354856e-14
2.5863137772202255e-14
2.586313777104966e-14
2.5863137769908733e-14
2.5863137768756135e-14
2.586313776760354e-14
2.5863137766462702e-14
2.5863137765310103e-14
2.586313776416927e-14
2.5863137763004913e-14
2.5863137761864078e-14
2.5863137760711483e-14
2.5863137759570645e-14
2.5863137758429718e-14
2.5863137757265357e-14
2.5863137756124525e-14
2.5863137754971926e-14
2.586313775383109e-14
2.586313775266673e-14
2.5863137751525898e-14
2.586313775038506e-14
2.5

2.586313665105807e-14
2.5863136649917234e-14
2.5863136648752875e-14
2.5863136647612037e-14
2.5863136646459442e-14
2.5863136645318607e-14
2.5863136644166012e-14
2.5863136643013322e-14
2.5863136641872484e-14
2.5863136640719886e-14
2.586313663956729e-14
2.5863136638414696e-14
2.5863136637273857e-14
2.5863136636133023e-14
2.5863136634980427e-14
2.5863136633827832e-14
2.5863136632675234e-14
2.58631366315343e-14
2.586313663039347e-14
2.586313662922911e-14
2.5863136628088276e-14
2.586313662693568e-14
2.5863136625794843e-14
2.5863136624630484e-14
2.586313662348965e-14
2.586313662234881e-14
2.5863136621196216e-14
2.586313662004362e-14
2.5863136618890928e-14
2.5863136617750096e-14
2.5863136616609258e-14
2.5863136615444902e-14
2.5863136614304064e-14
2.586313661315147e-14
2.586313661201063e-14
2.5863136610846276e-14
2.5863136609705438e-14
2.5863136608564606e-14
2.5863136607412004e-14
2.5863136606271078e-14
2.5863136605106722e-14
2.5863136603965884e-14
2.5863136602825053e-14
2.586313660167245e-14
2

2.586313564937328e-14
2.5863135648232442e-14
2.5863135647079844e-14
2.586313564592725e-14
2.5863135644774653e-14
2.5863135643633818e-14
2.5863135642481217e-14
2.5863135641328622e-14
2.586313564018779e-14
2.5863135639035192e-14
2.5863135637894265e-14
2.5863135636729907e-14
2.586313563558907e-14
2.5863135634448234e-14
2.586313563329564e-14
2.5863135632143037e-14
2.5863135630990442e-14
2.586313562984961e-14
2.5863135628697012e-14
2.5863135627556174e-14
2.5863135626403484e-14
2.586313562525089e-14
2.5863135624110054e-14
2.586313562295746e-14
2.5863135621804863e-14
2.5863135620664025e-14
2.5863135619511427e-14
2.586313561837059e-14
2.5863135617206237e-14
2.58631356160654e-14
2.5863135614912803e-14
2.5863135613771874e-14
2.586313561261928e-14
2.5863135611466683e-14
2.5863135610325845e-14
2.5863135609173247e-14
2.5863135608020652e-14
2.5863135606879814e-14
2.586313560572722e-14
2.5863135604586384e-14
2.5863135603433782e-14
2.58631356022811e-14
2.5863135601128503e-14
2.5863135599987665e-14
2.5

2.586313513131242e-14
2.586313513014806e-14
2.5863135129007227e-14
2.586313512785463e-14
2.5863135126713793e-14
2.5863135125561198e-14
2.5863135124408603e-14
2.5863135123267673e-14
2.5863135122115078e-14
2.5863135120962483e-14
2.586313511980988e-14
2.5863135118669047e-14
2.586313511752821e-14
2.5863135116363856e-14
2.5863135115223018e-14
2.5863135114070423e-14
2.5863135112929585e-14
2.5863135111788655e-14
2.5863135110624303e-14
2.5863135109483465e-14
2.586313510833087e-14
2.5863135107190032e-14
2.5863135106025676e-14
2.5863135104884838e-14
2.5863135103744007e-14
2.5863135102591405e-14
2.5863135101438807e-14
2.586313510028621e-14
2.5863135099145285e-14
2.5863135098004447e-14
2.586313509684009e-14
2.5863135095699254e-14
2.5863135094546658e-14
2.5863135093405827e-14
2.5863135092241465e-14
2.5863135091100627e-14
2.5863135089959795e-14
2.58631350888072e-14
2.5863135087666267e-14
2.5863135086501912e-14
2.5863135085361074e-14
2.5863135084220242e-14
2.5863135083067647e-14
2.5863135081915045e-1

2.586313437890808e-14
2.586313437775548e-14
2.5863134376602796e-14
2.5863134375461958e-14
2.586313437430936e-14
2.5863134373156764e-14
2.5863134372015926e-14
2.586313437086333e-14
2.58631343697225e-14
2.5863134368558138e-14
2.58631343674173e-14
2.5863134366276468e-14
2.5863134365123873e-14
2.5863134363971183e-14
2.5863134362818584e-14
2.5863134361677746e-14
2.586313436052515e-14
2.5863134359372556e-14
2.5863134358231718e-14
2.5863134357079123e-14
2.5863134355926524e-14
2.5863134354762166e-14
2.5863134353621334e-14
2.5863134352480408e-14
2.586313435132781e-14
2.586313435018697e-14
2.5863134349022613e-14
2.586313434788178e-14
2.5863134346729186e-14
2.5863134345588348e-14
2.586313434443575e-14
2.5863134343283154e-14
2.5863134342142316e-14
2.586313434098972e-14
2.586313433983703e-14
2.5863134338696196e-14
2.58631343375436e-14
2.5863134336402763e-14
2.5863134335238404e-14
2.5863134334097573e-14
2.5863134332944974e-14
2.5863134331804136e-14
2.586313433065154e-14
2.5863134329498946e-14
2.5863

2.5863133447297106e-14
2.5863133446144507e-14
2.586313344500358e-14
2.5863133443850986e-14
2.586313344269839e-14
2.5863133441545795e-14
2.5863133440404957e-14
2.5863133439264123e-14
2.5863133438099764e-14
2.5863133436958926e-14
2.586313343580633e-14
2.58631334346655e-14
2.5863133433512897e-14
2.586313343236021e-14
2.5863133431219373e-14
2.5863133430066777e-14
2.5863133428914182e-14
2.5863133427761587e-14
2.586313342662075e-14
2.5863133425479914e-14
2.5863133424315556e-14
2.5863133423174717e-14
2.5863133422022122e-14
2.5863133420881196e-14
2.5863133419740358e-14
2.5863133418576002e-14
2.5863133417435164e-14
2.586313341628257e-14
2.586313341514173e-14
2.586313341397738e-14
2.586313341283654e-14
2.5863133411695706e-14
2.5863133410543104e-14
2.586313340939051e-14
2.5863133408237826e-14
2.5863133407085224e-14
2.586313340593263e-14
2.586313340478003e-14
2.58631334036392e-14
2.5863133402486597e-14
2.5863133401345766e-14
2.5863133400181407e-14
2.5863133399040572e-14
2.5863133397899734e-14
2.58

2.5863132887860053e-14
2.586313288671922e-14
2.586313288556662e-14
2.5863132884414024e-14
2.5863132883273193e-14
2.5863132882120503e-14
2.5863132880979665e-14
2.5863132879827066e-14
2.586313287867447e-14
2.5863132877521876e-14
2.5863132876381038e-14
2.5863132875240206e-14
2.5863132874075848e-14
2.5863132872935013e-14
2.586313287178241e-14
2.586313287064158e-14
2.586313286948889e-14
2.5863132868336294e-14
2.5863132867195456e-14
2.586313286604286e-14
2.5863132864890263e-14
2.5863132863737668e-14
2.586313286259683e-14
2.5863132861455998e-14
2.586313286029164e-14
2.5863132859150808e-14
2.5863132857998206e-14
2.586313285685728e-14
2.586313285570468e-14
2.5863132854552086e-14
2.5863132853411248e-14
2.5863132852258653e-14
2.586313285111782e-14
2.586313284995346e-14
2.5863132848812624e-14
2.586313284767179e-14
2.5863132846519194e-14
2.58631328453666e-14
2.586313284421391e-14
2.586313284307307e-14
2.5863132841920476e-14
2.5863132840767878e-14
2.586313283962704e-14
2.5863132838474445e-14
2.58631

2.5863132423783488e-14
2.586313242264265e-14
2.586313242149005e-14
2.5863132420337456e-14
2.5863132419196625e-14
2.5863132418044023e-14
2.5863132416891428e-14
2.58631324157505e-14
2.5863132414597906e-14
2.5863132413457068e-14
2.586313241230447e-14
2.5863132411151875e-14
2.586313240999928e-14
2.586313240885844e-14
2.586313240771761e-14
2.586313240655325e-14
2.5863132405412413e-14
2.5863132404259815e-14
2.5863132403118888e-14
2.5863132401966293e-14
2.5863132400813698e-14
2.586313239967286e-14
2.5863132398520265e-14
2.586313239736767e-14
2.586313239621507e-14
2.5863132395074233e-14
2.58631323939334e-14
2.5863132392769043e-14
2.5863132391628116e-14
2.586313239047552e-14
2.5863132389334683e-14
2.5863132388193848e-14
2.586313238702949e-14
2.5863132385888652e-14
2.5863132384736056e-14
2.5863132383595218e-14
2.5863132382430866e-14
2.5863132381290028e-14
2.5863132380149196e-14
2.5863132378996503e-14
2.5863132377843908e-14
2.5863132376691313e-14
2.5863132375550475e-14
2.5863132374409637e-14
2.58

2.5863131115399998e-14
2.5863131114247403e-14
2.586313111310657e-14
2.5863131111965733e-14
2.5863131110813138e-14
2.586313110966054e-14
2.586313110850794e-14
2.5863131107367107e-14
2.586313110622627e-14
2.586313110506182e-14
2.5863131103920983e-14
2.5863131102768388e-14
2.5863131101627557e-14
2.5863131100463198e-14
2.586313109932236e-14
2.5863131098181528e-14
2.586313109702893e-14
2.586313109587633e-14
2.5863131094723733e-14
2.58631310935829e-14
2.5863131092441975e-14
2.5863131091289373e-14
2.5863131090136778e-14
2.5863131088984183e-14
2.5863131087843345e-14
2.586313108669075e-14
2.5863131085538155e-14
2.586313108439732e-14
2.586313108324472e-14
2.5863131082103887e-14
2.5863131080939528e-14
2.5863131079786838e-14
2.5863131078646006e-14
2.586313107749341e-14
2.586313107634081e-14
2.5863131075188214e-14
2.5863131074047383e-14
2.586313107289478e-14
2.5863131071742186e-14
2.586313107060135e-14
2.5863131069448756e-14
2.5863131068307823e-14
2.5863131067155228e-14
2.5863131066002633e-14
2.586

2.586313017575625e-14
2.5863130174603656e-14
2.586313017346273e-14
2.5863130172310134e-14
2.5863130171169296e-14
2.5863130170004938e-14
2.5863130168864106e-14
2.586313016771151e-14
2.5863130166570673e-14
2.5863130165418078e-14
2.586313016426548e-14
2.5863130163124644e-14
2.5863130161971954e-14
2.5863130160819356e-14
2.586313015967852e-14
2.5863130158525923e-14
2.586313015738509e-14
2.5863130156232496e-14
2.5863130155079894e-14
2.58631301539273e-14
2.5863130152786468e-14
2.586313015164563e-14
2.586313015048127e-14
2.5863130149340344e-14
2.586313014818775e-14
2.586313014704691e-14
2.5863130145894316e-14
2.586313014474172e-14
2.5863130143600883e-14
2.5863130142448284e-14
2.586313014129569e-14
2.5863130140143094e-14
2.5863130139002256e-14
2.5863130137861424e-14
2.586313013669697e-14
2.586313013555614e-14
2.5863130134403544e-14
2.5863130133262706e-14
2.586313013211011e-14
2.5863130130945752e-14
2.5863130129804914e-14
2.586313012865232e-14
2.5863130127511484e-14
2.5863130126347125e-14
2.5863

2.5863129190161113e-14
2.5863129189020275e-14
2.586312918786768e-14
2.5863129186715085e-14
2.586312918556249e-14
2.5863129184421652e-14
2.586312918328082e-14
2.5863129182104698e-14
2.586312918096377e-14
2.5863129179811176e-14
2.5863129178670338e-14
2.5863129177529503e-14
2.5863129176365145e-14
2.586312917522431e-14
2.586312917407171e-14
2.586312917293088e-14
2.586312917176652e-14
2.5863129170625683e-14
2.586312916948485e-14
2.586312916833216e-14
2.5863129167179566e-14
2.5863129166026965e-14
2.5863129164886133e-14
2.5863129163745295e-14
2.5863129162580936e-14
2.5863129161440105e-14
2.586312916028751e-14
2.586312915914667e-14
2.5863129157982313e-14
2.5863129156841386e-14
2.5863129155700555e-14
2.5863129154547953e-14
2.5863129153395358e-14
2.5863129152242763e-14
2.5863129151101925e-14
2.586312914994933e-14
2.5863129148808498e-14
2.5863129147655896e-14
2.58631291465033e-14
2.586312914536247e-14
2.586312914420978e-14
2.586312914305718e-14
2.5863129141916346e-14
2.586312914076375e-14
2.58631

2.5863128616951707e-14
2.5863128615799112e-14
2.5863128614658274e-14
2.586312861349392e-14
2.5863128612353083e-14
2.5863128611212245e-14
2.586312861005965e-14
2.586312860891882e-14
2.586312860775446e-14
2.5863128606613622e-14
2.5863128605472695e-14
2.58631286043201e-14
2.5863128603167505e-14
2.586312860201491e-14
2.5863128600874072e-14
2.5863128599721477e-14
2.586312859856888e-14
2.5863128597428043e-14
2.5863128596275448e-14
2.586312859513461e-14
2.586312859397025e-14
2.5863128592829325e-14
2.5863128591688493e-14
2.5863128590535892e-14
2.586312858939506e-14
2.58631285882307e-14
2.5863128587089863e-14
2.5863128585937268e-14
2.5863128584796437e-14
2.5863128583643835e-14
2.586312858249124e-14
2.5863128581350405e-14
2.5863128580197718e-14
2.586312857903336e-14
2.5863128577892525e-14
2.5863128576739926e-14
2.586312857559909e-14
2.5863128574434733e-14
2.5863128573293898e-14
2.58631285721413e-14
2.5863128571000468e-14
2.586312856984787e-14
2.5863128568695183e-14
2.5863128567554345e-14
2.58631

2.5863127468239597e-14
2.5863127467098765e-14
2.5863127465934312e-14
2.586312746479348e-14
2.5863127463652642e-14
2.5863127462500047e-14
2.5863127461347452e-14
2.586312746019485e-14
2.586312745905402e-14
2.586312745788966e-14
2.5863127456748822e-14
2.5863127455596227e-14
2.586312745444363e-14
2.5863127453302705e-14
2.586312745215011e-14
2.5863127450997515e-14
2.5863127449856677e-14
2.586312744870408e-14
2.5863127447563243e-14
2.5863127446398885e-14
2.5863127445258053e-14
2.586312744410545e-14
2.586312744296462e-14
2.586312744181193e-14
2.5863127440659335e-14
2.58631274395185e-14
2.58631274383659e-14
2.5863127437213306e-14
2.586312743607247e-14
2.5863127434919876e-14
2.586312743377904e-14
2.5863127432626443e-14
2.5863127431473848e-14
2.586312743032125e-14
2.5863127429180326e-14
2.5863127428039488e-14
2.586312742687513e-14
2.5863127425734298e-14
2.5863127424581702e-14
2.5863127423440864e-14
2.586312742228827e-14
2.5863127421135668e-14
2.5863127419994836e-14
2.586312741884224e-14
2.586312

2.586312656534988e-14
2.5863126564197284e-14
2.586312656304469e-14
2.586312656190385e-14
2.5863126560751256e-14
2.5863126559598566e-14
2.586312655845773e-14
2.5863126557305136e-14
2.58631265561643e-14
2.5863126554999946e-14
2.5863126553859108e-14
2.5863126552706512e-14
2.5863126551565674e-14
2.5863126550424843e-14
2.5863126549260484e-14
2.5863126548119646e-14
2.5863126546966962e-14
2.5863126545826124e-14
2.5863126544661766e-14
2.5863126543520928e-14
2.5863126542380096e-14
2.58631265412275e-14
2.58631265400749e-14
2.5863126538922304e-14
2.5863126537781472e-14
2.5863126536640634e-14
2.586312653547628e-14
2.5863126534335352e-14
2.5863126533182757e-14
2.586312653204192e-14
2.586312653087756e-14
2.586312652973673e-14
2.586312652859589e-14
2.5863126527443296e-14
2.5863126526302458e-14
2.5863126525138105e-14
2.5863126523997267e-14
2.586312652285643e-14
2.5863126521703746e-14
2.5863126520551144e-14
2.586312651939855e-14
2.5863126518257717e-14
2.5863126517105116e-14
2.586312651595252e-14
2.5863

2.5863125772733918e-14
2.5863125771581322e-14
2.5863125770440488e-14
2.586312576928789e-14
2.5863125768135294e-14
2.5863125766994462e-14
2.586312576584186e-14
2.586312576470103e-14
2.5863125763548434e-14
2.5863125762395744e-14
2.5863125761254906e-14
2.586312576010231e-14
2.5863125758949716e-14
2.586312575779712e-14
2.5863125756656282e-14
2.5863125755515447e-14
2.586312575435109e-14
2.5863125753210257e-14
2.5863125752057662e-14
2.586312575091673e-14
2.5863125749764134e-14
2.586312574861154e-14
2.58631257474707e-14
2.5863125746318106e-14
2.586312574516551e-14
2.5863125744012915e-14
2.5863125742872077e-14
2.5863125741731245e-14
2.5863125740578647e-14
2.5863125739426052e-14
2.5863125738273362e-14
2.586312573713253e-14
2.5863125735991692e-14
2.5863125734827334e-14
2.5863125733674738e-14
2.5863125732522143e-14
2.5863125731381305e-14
2.5863125730216946e-14
2.5863125729076115e-14
2.5863125727935277e-14
2.586312572678268e-14
2.5863125725629992e-14
2.5863125724477396e-14
2.5863125723336562e-14
2

2.5863124958300887e-14
2.5863124957136528e-14
2.5863124955995694e-14
2.5863124954854862e-14
2.586312495369041e-14
2.5863124952549577e-14
2.5863124951396975e-14
2.5863124950256144e-14
2.5863124949103548e-14
2.5863124947950947e-14
2.5863124946810115e-14
2.5863124945657517e-14
2.586312494450492e-14
2.5863124943352326e-14
2.58631249422114e-14
2.5863124941070562e-14
2.5863124939906203e-14
2.586312493876537e-14
2.5863124937612776e-14
2.5863124936471938e-14
2.5863124935319343e-14
2.5863124934166745e-14
2.586312493302591e-14
2.5863124931873315e-14
2.586312493073248e-14
2.5863124929568033e-14
2.5863124928427195e-14
2.5863124927286357e-14
2.586312492613376e-14
2.5863124924981166e-14
2.586312492382857e-14
2.5863124922687733e-14
2.5863124921546898e-14
2.5863124920382543e-14
2.5863124919241708e-14
2.5863124918089113e-14
2.5863124916948186e-14
2.5863124915783828e-14
2.586312491464299e-14
2.5863124913502158e-14
2.5863124912349556e-14
2.586312491119696e-14
2.5863124910044366e-14
2.586312490890353e-14


2.586312421392973e-14
2.5863124212788898e-14
2.586312421162454e-14
2.5863124210483702e-14
2.586312420934287e-14
2.586312420819027e-14
2.5863124207037585e-14
2.5863124205884986e-14
2.5863124204744155e-14
2.5863124203603317e-14
2.5863124202438958e-14
2.5863124201298126e-14
2.5863124200145525e-14
2.5863124199004693e-14
2.5863124197852098e-14
2.58631241966995e-14
2.5863124195558668e-14
2.5863124194405978e-14
2.586312419326514e-14
2.586312419210078e-14
2.586312419095995e-14
2.5863124189819115e-14
2.586312418866652e-14
2.5863124187513924e-14
2.5863124186361323e-14
2.586312418522049e-14
2.5863124184067896e-14
2.5863124182915294e-14
2.586312418176261e-14
2.586312418061001e-14
2.5863124179469178e-14
2.5863124178304822e-14
2.5863124177163984e-14
2.5863124176023152e-14
2.586312417487055e-14
2.586312417372972e-14
2.586312417256536e-14
2.5863124171424522e-14
2.5863124170271927e-14
2.5863124169131004e-14
2.586312416797841e-14
2.5863124166825807e-14
2.5863124165684976e-14
2.586312416453238e-14
2.5863

2.5863123398344057e-14
2.5863123397179705e-14
2.586312339603887e-14
2.5863123394898032e-14
2.5863123393745437e-14
2.586312339259284e-14
2.5863123391440246e-14
2.5863123390299408e-14
2.5863123389158573e-14
2.5863123388005978e-14
2.5863123386853383e-14
2.5863123385700693e-14
2.5863123384559855e-14
2.586312338340726e-14
2.5863123382254665e-14
2.586312338111383e-14
2.5863123379961234e-14
2.5863123378820396e-14
2.5863123377656044e-14
2.5863123376515206e-14
2.586312337536261e-14
2.5863123374221773e-14
2.5863123373069086e-14
2.586312337191649e-14
2.5863123370775653e-14
2.5863123369623058e-14
2.5863123368470462e-14
2.5863123367329624e-14
2.586312336617703e-14
2.5863123365036194e-14
2.5863123363871836e-14
2.5863123362731004e-14
2.586312336157841e-14
2.5863123360437476e-14
2.5863123359296644e-14
2.5863123358132286e-14
2.586312335699145e-14
2.5863123355838856e-14
2.5863123354698018e-14
2.5863123353545422e-14
2.5863123352392827e-14
2.5863123351251992e-14
2.5863123350099397e-14
2.5863123348946707e-

2.586312210373356e-14
2.586312210259273e-14
2.5863122101440134e-14
2.5863122100287533e-14
2.586312209914661e-14
2.5863122097994014e-14
2.5863122096853176e-14
2.5863122095688818e-14
2.5863122094547986e-14
2.586312209340715e-14
2.5863122092254556e-14
2.586312209110196e-14
2.586312208994936e-14
2.5863122088808527e-14
2.586312208765593e-14
2.5863122086515003e-14
2.5863122085362408e-14
2.5863122084209812e-14
2.5863122083068974e-14
2.586312208191638e-14
2.5863122080763784e-14
2.5863122079611186e-14
2.5863122078470354e-14
2.5863122077329516e-14
2.5863122076165157e-14
2.5863122075024234e-14
2.586312207387164e-14
2.58631220727308e-14
2.5863122071578205e-14
2.586312207042561e-14
2.5863122069284775e-14
2.586312206813218e-14
2.586312206697958e-14
2.5863122065826984e-14
2.5863122064686145e-14
2.5863122063545314e-14
2.5863122062392627e-14
2.5863122061240032e-14
2.5863122060087437e-14
2.58631220589466e-14
2.5863122057805764e-14
2.5863122056641405e-14
2.5863122055500573e-14
2.5863122054347972e-14
2.58

2.5863121154892715e-14
2.5863121153751877e-14
2.586312115261104e-14
2.5863121151458447e-14
2.5863121150305852e-14
2.5863121149153257e-14
2.586312114801242e-14
2.5863121146859823e-14
2.5863121145707225e-14
2.5863121144566393e-14
2.5863121143413704e-14
2.5863121142272866e-14
2.586312114110851e-14
2.5863121139967678e-14
2.586312113882684e-14
2.5863121137674245e-14
2.586312113652165e-14
2.586312113536905e-14
2.586312113422822e-14
2.5863121133075618e-14
2.5863121131934787e-14
2.5863121130782097e-14
2.5863121129629505e-14
2.5863121128488667e-14
2.586312112733607e-14
2.586312112618347e-14
2.5863121125042638e-14
2.5863121123890046e-14
2.5863121122749208e-14
2.586312112158485e-14
2.5863121120444015e-14
2.5863121119291328e-14
2.5863121118150493e-14
2.5863121116997898e-14
2.5863121115845296e-14
2.5863121114704465e-14
2.5863121113551866e-14
2.586312111239927e-14
2.586312111125844e-14
2.5863121110105838e-14
2.5863121108965006e-14
2.586312110780065e-14
2.5863121106659724e-14
2.5863121105507123e-14
2

In [27]:
single_pt = np.array([ctmeans])
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)

single_pt = np.array([ctmeans1])
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)

single_pt = np.array([otmeans])
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)

[[1.]]
[[1.]]
[[7.41625237e-72]]


In [103]:
single_pt = np.array([otrnfeature])
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)

[[0.82314537]]


In [ ]:
single_pt = np.array([[0,0,0,0]])
result = sigmoid(np.dot(single_pt, weights) + bias)
print(result)